name: Agent CI

on:
  push:
    paths:
      - 'agent/**'
      - '.github/workflows/agent-ci.yml'
  pull_request:
    paths:
      - 'agent/**'
      - '.github/workflows/agent-ci.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Verify Go build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agent
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: agent/go.mod
          check-latest: true

      - name: Verify dependencies
        run: go mod verify

      - name: Build binaries
        run: go build ./...
